### ISSUE TITLE
Hello from Your NETGEAR Control Point

### ISSUE THREAD

**Issue by relains** [Mhynlo/rn-couchpotato#1]
Hello,

When I try to launch configuration web page of CouchPotatoServer I've got a message:
"Hello from Your NETGEAR Control Point" and nothing else. Anyone know a solution?

**Comment by Mhynlo** [comment]
What firmware are you running on the ReadyNAS?
That doesn't sound like anything directly related to my app, but something that is happening on the ReadyNAS side.

**Comment by relains** [comment]
I'm using the 6.4.2 version of firmware. Previously I used Couchpotato plugin from https://rnxtras.com but I had lot's of problems with it so I decided to change.

**Comment by Mhynlo** [comment]
That is interesting...
I am using the default port on CouchPotato (5050) which might be a similar port as Genie Marketplace (5050). Do you see an option for disabling Genie Marketplace?
https://community.netgear.com/t5/Current-NETGEAR-and-Partners/Genie-Marketplace-RN314/td-p/889069

I did not see that service still being available in the newer versions. If you don't see an option to disable that service; I can see if there is a good contact at Netgear for you to talk to about resolving this issue.

**Comment by relains** [comment]
After upgrading to firmware 6.5.0 problem disappeared. Thanks for the help anyway.
