### ISSUE TITLE
Auto updater on initial install works, but sucks afterwards; cleaning sucks

### ISSUE THREAD

**Issue by didyouexpectthat** [Mhynlo/rn-couchpotato#2]
You know the problem!
Fix it.
:)
Even apt-get install --reinstall couchpotato doesn't work.

**Comment by didyouexpectthat** [comment]
Is it fixed yet?

**Comment by Mhynlo** [comment]
I got most of the base structure built. I need to see if I have better handle migration for users that are running into the issue.
I have access to a box that is running into the issue to give me an idea of what files were impacted.

**Comment by Mhynlo** [comment]
Try this build:
https://github.com/Mhynlo/rn-couchpotato/releases/tag/2017.03.26-0

It was able to install and migrates to the newer setup while keeping the config intact.

**Comment by didyouexpectthat** [comment]
I had some issues with the service file from /lib not getting replaced by symlink. I replaced it and restarted service and and eventually came up.

**Comment by Mhynlo** [comment]
I wasn't able to reproduce that issue.
It should be handled in most cases.
