### ISSUE TITLE
Username/Password not working

### ISSUE THREAD

**Issue by Coolfeather2** [Mhynlo/rn-couchpotato#3]
After installing couchpotato on my readynas 214 and going through the setup/wizard I cannot login using the username/password I typed in

**Comment by Mhynlo** [comment]
The app by default does not have a login requirement.
There is a setting to configure the username/password in the initial setup wizard. That is working for me and is based from the CouchPotato's code.

Did you configure the CouchPotato app with the login? Or are you getting a login prompt from another means?
(I haven't been able to reproduce your issue.)

**Comment by Coolfeather2** [comment]
1. Clean Install
2. Set username to 'Coolfeather2'
3. Set password to random 100 length using characters, numbers and symbols
4. Finalize settings, ie "I'm ready to start the awesomeness!"
5. Enter Coolfeather2 for username
6. Enter my password
7. Click login and nothing happens


aand of course as I'm writing this and going through the method it works x-x
